'use client';

import * as React from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card';
import { loginAction } from '@/lib/actions/auth.actions';
import { LogIn, ShieldCheck, ArrowLeft } from 'lucide-react';

export default function LoginPage() {
  const [error, setError] = React.useState<string | null>(null);
  const [loading, setLoading] = React.useState(false);
  const [requiresMfa, setRequiresMfa] = React.useState(false);
  const [savedEmail, setSavedEmail] = React.useState('');
  const [savedPassword, setSavedPassword] = React.useState('');

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError(null);
    setLoading(true);

    const formData = new FormData(e.currentTarget);
    if (!requiresMfa) {
      setSavedEmail(String(formData.get('email') || ''));
      setSavedPassword(String(formData.get('password') || ''));
    } else {
      formData.set('email', savedEmail);
      formData.set('password', savedPassword);
    }

    try {
      const res = await loginAction(null, formData);
      if (res?.requiresMfa) {
        setRequiresMfa(true);
        if (res.error) {
          setError(res.error);
        }
        setLoading(false);
      } else if (res?.error) {
        setError(res.error);
        setLoading(false);
      }
    } catch (err: any) {
      if (err.message && !err.message.includes('NEXT_REDIRECT')) {
        setError(err.message);
        setLoading(false);
      }
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4 bg-slate-50 dark:bg-slate-950">
      <div className="w-full max-w-md space-y-6">
        <div className="text-center space-y-2">
          <Link href="/" className="inline-flex items-center gap-2">
            <div className="h-10 w-10 rounded-xl bg-emerald-600 flex items-center justify-center text-white font-bold shadow-md">
              DN
            </div>
            <span className="font-bold text-2xl text-slate-900 dark:text-white">DenaNeya</span>
          </Link>
          <p className="text-xs text-emerald-600 dark:text-emerald-400 font-medium font-bengali">
            দেনা-নেওয়া সহজ, হিসাব নিশ্চিত
          </p>
        </div>

        <Card className="border-slate-200 dark:border-slate-800 shadow-xl">
          <CardHeader className="space-y-1">
            <CardTitle className="text-xl font-bold">
              {requiresMfa ? 'Two-Factor Authentication' : 'Sign in to your account'}
            </CardTitle>
            <CardDescription className="text-xs">
              {requiresMfa
                ? 'Enter the 6-digit code from your authenticator app to complete sign-in.'
                : 'Enter your registered merchant or admin email and password.'}
            </CardDescription>
          </CardHeader>
          <form onSubmit={handleSubmit}>
            <CardContent className="space-y-4">
              {error && (
                <div className="p-3 rounded-lg bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-800 text-xs text-red-600 dark:text-red-400">
                  {error}
                </div>
              )}

              {requiresMfa ? (
                <>
                  <input type="hidden" name="email" value={savedEmail} />
                  <input type="hidden" name="password" value={savedPassword} />
                  <div className="space-y-2">
                    <Input
                      label="Authenticator Code (6 digits)"
                      name="mfaCode"
                      type="text"
                      inputMode="numeric"
                      pattern="[0-9]{6}"
                      maxLength={6}
                      placeholder="123456"
                      required
                      autoFocus
                      className="font-mono text-center tracking-widest text-lg"
                    />
                    <p className="text-[11px] text-slate-500 text-center">
                      Time-based OTP code generated by your Authenticator app.
                    </p>
                  </div>
                </>
              ) : (
                <>
                  <Input
                    label="Email Address"
                    name="email"
                    type="email"
                    placeholder="merchant@company.com.bd"
                    required
                    autoComplete="email"
                  />
                  <Input
                    label="Password"
                    name="password"
                    type="password"
                    placeholder="••••••••"
                    required
                    autoComplete="current-password"
                  />
                  <div className="flex items-center justify-between text-xs">
                    <label className="flex items-center gap-2 text-slate-600 dark:text-slate-400 cursor-pointer">
                      <input type="checkbox" className="rounded border-slate-300 text-emerald-600 focus:ring-emerald-500" />
                      Remember me
                    </label>
                    <Link href="/forgot-password" className="text-emerald-600 hover:underline">
                      Forgot password?
                    </Link>
                  </div>
                </>
              )}
            </CardContent>
            <CardFooter className="flex flex-col space-y-4">
              <Button type="submit" disabled={loading} className="w-full gap-2">
                {requiresMfa ? <ShieldCheck className="w-4 h-4" /> : <LogIn className="w-4 h-4" />}
                {loading ? 'Verifying...' : requiresMfa ? 'Verify & Sign In' : 'Sign In'}
              </Button>

              {requiresMfa && (
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  onClick={() => {
                    setRequiresMfa(false);
                    setError(null);
                  }}
                  className="w-full gap-2 text-xs text-slate-500"
                >
                  <ArrowLeft className="w-3.5 h-3.5" /> Back to password sign in
                </Button>
              )}

              {!requiresMfa && (
                <div className="text-center text-xs text-slate-500">
                  Don&apos;t have a merchant account?{' '}
                  <Link href="/register" className="text-emerald-600 font-semibold hover:underline">
                    Register for Free
                  </Link>
                </div>
              )}
            </CardFooter>
          </form>
        </Card>
      </div>
    </div>
  );
}
